const Map<String, String> arSA = {
  "choose_your_language": "اختر لغتك",
  "english": "الإنجليزية",
  "continue": "متابعة",
  "enter_phone_number": "أدخل رقم الهاتف",
  "something_went_wrong": "حدث خطأ ما",
  "create_account": "إنشاء حساب",
  "first_name": "الاسم الأول",
  "last_name": "اسم العائلة",
  "email": "البريد الإلكتروني",
  "phone_number": "رقم الهاتف",
  "please_fill_all_fields": "يرجى ملء جميع الحقول",
  "signup_failed": "فشل التسجيل",
  "verify_otp": "التحقق من OTP",
  "enter_the_otp_sent_to_your_number": "أدخل رمز OTP المرسل إلى رقمك",
  "verify": "تحقق",
  "enter_valid_otp": "أدخل OTP صالح",
  "invalid_customer_id": "معرف العميل غير صالح",
  "otp_verification_failed": "فشل التحقق من OTP",
  "my_bookings": "حجوزاتي",
  "aguawash": "AGUAWASH",
  "no_services_available": "لا توجد خدمات متاحة",
  "book_now": "احجز الآن",
  "doorstep_car_wash": "غسيل سيارات عند المنزل",
  "convenience_at_your_home": "الراحة في منزلك",
  "in_store_car_wash": "غسيل سيارات داخل المتجر",
  "visit_us_for_a_premium_clean": "زرنا للحصول على تنظيف مميز",
  "off_50": "خصم 50%",
  "expires_in": "ينتهي خلال",
  "days": "أيام",
  "not_assigned": "غير معين",
  "assigned": "تم التعيين",
  "arrived": "وصل",
  "in_progress": "قيد التنفيذ",
  "completed": "مكتمل",
  "booking_cancelled_successfully": "تم إلغاء الحجز بنجاح",
  "failed_to_cancel_booking": "فشل إلغاء الحجز",
  "current_booking": "الحجز الحالي",
  "past_bookings": "الحجوزات السابقة",
  "edit_booking": "تعديل الحجز",
  "do_you_want_to_edit_this_booking": "هل تريد تعديل هذا الحجز؟",
  "yes_edit": "نعم، تعديل",
  "no": "لا",
  "cancel_booking": "إلغاء الحجز",
  "are_you_sure_you_want_to_cancel_this_booking":
      "هل أنت متأكد أنك تريد إلغاء هذا الحجز؟",
  "yes_cancel": "نعم، إلغاء",
  "cancel": "إلغاء",
  "view_details": "عرض التفاصيل",
  "my_profile": "ملفي الشخصي",
  "no_email": "لا يوجد بريد إلكتروني",
  "my_cars": "سياراتي",
  "my_locations": "مواقعي",
  "language_selection": "اختيار اللغة",
  "my_coupons": "كوبوناتي",
  "offers": "العروض",
  "logout": "تسجيل الخروج",
  "are_you_sure_you_want_to_logout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "add_vehicle": "إضافة مركبة",
  "save_vehicle": "حفظ المركبة",
  "vehicle_number": "رقم المركبة",
  "brand": "العلامة التجارية",
  "model": "الموديل",
  "type_sedan_suv_etc": "النوع (سيدان، SUV، إلخ)",
  "this_vehicle_number_already_exists": "رقم المركبة هذا موجود بالفعل",
  "vehicle_added_successfully": "تمت إضافة المركبة بنجاح",
  "unable_to_add_vehicle": "تعذر إضافة المركبة",
  "search_an_area_or_address": "ابحث عن منطقة أو عنوان",
  "current_location": "الموقع الحالي",
  "order_will_be_delivered_here": "سيتم توصيل الطلب هنا",
  "my_vehicles": "مركباتي",
  "no_vehicles_added": "لم تتم إضافة أي مركبات",
  "coupon_details": "تفاصيل الكوبون",
  "coupon_not_found": "الكوبون غير موجود",
  "redeem_discount_message":
      "يمكنك إظهار هذا الرمز عند الكاشير لاسترداد الخصم.",
  "active": "نشط",
  "no_coupons_available": "لا توجد كوبونات متاحة",
  "youve_got_new_rewards": "لقد حصلت على مكافآت جديدة!",
  "use_now": "استخدم الآن",
  "not_active": "غير نشط",
  "help_support": "المساعدة والدعم",
  "find_quick_answers_to_your_questions": "اعثر على إجابات سريعة لأسئلتك",
  "frequently_asked_questions": "الأسئلة الشائعة",
  "answer": "الإجابة",
  "contact_support_message": "املأ النموذج أدناه — نرد عادة خلال 24 ساعة.",
  "contact_support": "اتصل بالدعم",
  "full_name": "الاسم الكامل",
  "email_optional": "البريد الإلكتروني (اختياري)",
  "mobile_number": "رقم الجوال",
  "general_inquiry": "استفسار عام",
  "booking_id_if_relevant": "رقم الحجز (إن وجد)",
  "describe_your_issue_or_question": "صف مشكلتك أو سؤالك",
  "send_message": "إرسال الرسالة",
  "change_language": "تغيير اللغة",
  "location_details": "تفاصيل الموقع",
  "house_number": "رقم المنزل",
  "enter_house_flat_number": "أدخل رقم المنزل/الشقة",
  "landmark_optional": "معلم قريب (اختياري)",
  "enter_nearby_landmark": "أدخل معلم قريب",
  "save_as": "حفظ باسم",
  "save_location": "حفظ الموقع",
  "home": "المنزل",
  "work": "العمل",
  "other": "أخرى",
  "please_enter_house_number": "يرجى إدخال رقم المنزل",
  "please_enter_phone_number": "يرجى إدخال رقم الهاتف",
  "location_updated_successfully": "تم تحديث الموقع بنجاح",
  "location_saved_successfully": "تم حفظ الموقع بنجاح",
  "addresses": "العناوين",
  "saved_addresses": "العناوين المحفوظة",
  "add_new_address": "إضافة عنوان جديد",
  "delete_address": "حذف العنوان",
  "are_you_sure_you_want_to_delete": "هل أنت متأكد أنك تريد الحذف",
  "delete": "حذف",
  "offer_details": "تفاصيل العرض",
  "no_description_available": "لا يوجد وصف متاح.",
  "terms_conditions": "الشروط والأحكام",
  "redeem_now": "استرد الآن",
  "no_offers_available": "لا توجد عروض متاحة",
  "visual_proof": "إثبات مرئي",
  "before": "قبل",
  "after": "بعد",
  "book_again": "احجز مرة أخرى",
  "date_time": "التاريخ والوقت",
  "service": "الخدمة",
  "payment": "الدفع",
  "no_images_available": "لا توجد صور متاحة",
  "no_media_available": "لا توجد وسائط متاحة",
  "confirm_car_wash": "تأكيد غسيل السيارة",
  "select_your_vehicle": "اختر مركبتك",
  "select_date_and_time": "اختر التاريخ والوقت",
  "service_details": "تفاصيل الخدمة",
  "add_new": "إضافة جديد",
  "please_select_a_date": "يرجى اختيار تاريخ",
  "no_slots_available_for_this_date": "لا توجد مواعيد متاحة لهذا التاريخ",
  "price_details": "تفاصيل السعر",
  "service_price": "سعر الخدمة",
  "vat": "ضريبة القيمة المضافة",
  "total_amount": "المبلغ الإجمالي",
  "confirm_book": "تأكيد الحجز",
  "customer_id_missing": "معرف العميل مفقود",
  "please_select_a_vehicle": "يرجى اختيار مركبة",
  "please_select_a_time_slot": "يرجى اختيار وقت",
  "invalid_slot_selected": "الوقت المحدد غير صالح",
  "please_select_a_slot": "يرجى اختيار موعد",
  "booking_updated_successfully": "تم تحديث الحجز بنجاح!",
  "failed_to_update_booking": "فشل تحديث الحجز",
  "booking_failed": "فشل الحجز",
  "booking_failed_try_again": "فشل الحجز. حاول مرة أخرى.",
  "location_saved": "تم حفظ الموقع",
  "error_selecting_location": "خطأ أثناء اختيار الموقع:",
  "your_coupon": "الكوبون الخاص بك",
  "coupon_not_available": "الكوبون غير متاح",
  "valid_till": "صالح حتى",
  "done": "تم",
  "booking_confirmed": "تم تأكيد الحجز!",
  "total": "الإجمالي",
  "door_step_services": "خدمات عند الباب",
  "in_store_locations": "مواقع المتجر",
  "search_by_name_or_area": "ابحث بالاسم أو المنطقة",
  "no_reviews_yet": "لا توجد مراجعات بعد",
  "view_reviews": "عرض المراجعات",
  "location": "الموقع",
  "call": "اتصال",
  "partner_locations_not_found":
      "لم نتمكن من العثور على مواقع شركاء. حاول مرة أخرى لاحقًا.",
  "pick_location": "اختر الموقع",
  "selected_location": "الموقع المحدد",
  "confirm_location": "تأكيد الموقع",
  "error": "خطأ",
  "please_select_a_location": "يرجى اختيار موقع",
  "payment_details": "تفاصيل الدفع",
  "confirm_service_details_before_payment":
      "أكد تفاصيل الخدمة قبل المتابعة للدفع.",
  "subtotal": "المجموع الفرعي",
  "tax": "الضريبة",
  "pay_now": "ادفع الآن",
  "payment_failed": "فشل الدفع",
  "payment_successful": "تم الدفع بنجاح",
  "tracking_service": "تتبع الخدمة",
  "live": "مباشر",
  "expected_soon": "متوقع قريبًا",
  "scheduled_at": "مجدول في",
  "technician_assigned": "تم تعيين الفني",
};
