const Map<String, String> enUS = {
  "choose_your_language": "Choose Your Language",
  "english": "English",
  "continue": "Continue",
  "enter_phone_number": "Enter phone number",
  "something_went_wrong": "Something went wrong",
  "create_account": "Create Account",
  "first_name": "First Name",
  "last_name": "Last Name",
  "email": "Email",
  "phone_number": "Phone Number",
  "please_fill_all_fields": "Please fill all fields",
  "signup_failed": "Signup failed",
  "verify_otp": "Verify OTP",
  "enter_the_otp_sent_to_your_number": "Enter the OTP sent to your number",
  "verify": "Verify",
  "enter_valid_otp": "Enter valid OTP",
  "invalid_customer_id": "Invalid customer ID",
  "otp_verification_failed": "OTP verification failed",
  "my_bookings": "My Bookings",
  "aguawash": "AGUAWASH",
  "no_services_available": "No services available",
  "book_now": "Book Now",
  "doorstep_car_wash": "Doorstep Car Wash",
  "convenience_at_your_home": "Convenience at your home",
  "in_store_car_wash": "In-Store Car Wash",
  "visit_us_for_a_premium_clean": "Visit us for a premium clean",
  "off_50": "50% OFF",
  "expires_in": "Expires in",
  "days": "days",
  "not_assigned": "Not Assigned",
  "assigned": "ASSIGNED",
  "arrived": "ARRIVED",
  "in_progress": "IN_PROGRESS",
  "completed": "COMPLETED",
  "booking_cancelled_successfully": "Booking cancelled successfully",
  "failed_to_cancel_booking": "Failed to cancel booking",
  "current_booking": "Current Booking",
  "past_bookings": "Past Bookings",
  "edit_booking": "Edit Booking",
  "do_you_want_to_edit_this_booking": "Do you want to edit this booking?",
  "yes_edit": "Yes, Edit",
  "no": "No",
  "cancel_booking": "Cancel Booking",
  "are_you_sure_you_want_to_cancel_this_booking":
      "Are you sure you want to cancel this booking?",
  "yes_cancel": "Yes, Cancel",
  "cancel": "Cancel",
  "view_details": "View Details",
  "my_profile": "My Profile",
  "no_email": "No Email",
  "my_cars": "My Cars",
  "my_locations": "My Locations",
  "language_selection": "Language Selection",
  "my_coupons": "My Coupons",
  "offers": "Offers",
  "logout": "Logout",
  "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
  "add_vehicle": "Add Vehicle",
  "save_vehicle": "Save Vehicle",
  "vehicle_number": "Vehicle Number",
  "brand": "Brand",
  "model": "Model",
  "type_sedan_suv_etc": "Type (Sedan, SUV, etc.)",
  "this_vehicle_number_already_exists": "This vehicle number already exists",
  "vehicle_added_successfully": "Vehicle added successfully",
  "unable_to_add_vehicle": "Unable to add vehicle",
  "search_an_area_or_address": "Search an area or address",
  "current_location": "Current location",
  "order_will_be_delivered_here": "Techincian will arrive here",
  "my_vehicles": "My Vehicles",
  "no_vehicles_added": "No Vehicles Added",
  "coupon_details": "Coupon Details",
  "coupon_not_found": "Coupon not found",
  "redeem_discount_message":
      "can this code at the terminal or show it to a cashier to redeem your discount.",
  "active": "ACTIVE",
  "no_coupons_available": "No coupons available",
  "youve_got_new_rewards": "You've got new rewards!",
  "use_now": "Use Now",
  "not_active": "Not Active",
  "help_support": "Help & Support",
  "find_quick_answers_to_your_questions":
      "Find quick answers to your questions",
  "frequently_asked_questions": "Frequently Asked Questions",
  "answer": "answer",
  "contact_support_message":
      "Fill the form below — we typically reply within 24 hours.",
  "contact_support": "Contact Support",
  "full_name": "Full name",
  "email_optional": "Email (optional)",
  "mobile_number": "Mobile number",
  "general_inquiry": "General inquiry",
  "booking_id_if_relevant": "Booking ID (if relevant)",
  "describe_your_issue_or_question": "Describe your issue or question",
  "send_message": "Send message",
  "change_language": "Change Language",
  "location_details": "Location Details",
  "house_number": "House Number",
  "enter_house_flat_number": "Enter house/flat number",
  "landmark_optional": "Landmark (Optional)",
  "enter_nearby_landmark": "Enter nearby landmark",
  "save_as": "Save As",
  "save_location": "Save Location",
  "home": "Home",
  "work": "Work",
  "other": "Other",
  "please_enter_house_number": "Please enter house number",
  "please_enter_phone_number": "Please enter phone number",
  "location_updated_successfully": "Location updated successfully",
  "location_saved_successfully": "Location saved successfully",
  "addresses": "Addresses",
  "saved_addresses": "Saved Addresses",
  "add_new_address": "Add New Address",
  "delete_address": "Delete Address",
  "are_you_sure_you_want_to_delete": "Are you sure you want to delete",
  "delete": "Delete",
  "offer_details": "Offer Details",
  "no_description_available": "No description available.",
  "terms_conditions": "Terms & Conditions",
  "redeem_now": "Redeem Now",
  "no_offers_available": "No offers available",
  "visual_proof": "VISUAL PROOF",
  "before": "Before",
  "after": "After",
  "book_again": "Book Again",
  "date_time": "Date & Time",
  "service": "Service",
  "payment": "Payment",
  "no_images_available": "No images available",
  "no_media_available": "No media available",
  "confirm_car_wash": "Confirm Car Wash",
  "select_your_vehicle": "Select Your Vehicle",
  "select_date_and_time": "Select Date and Time",
  "service_details": "SERVICE DETAILS",
  "add_new": "Add New",
  "please_select_a_date": "Please select a date",
  "no_slots_available_for_this_date": "No slots available for this date",
  "price_details": "Price Details",
  "service_price": "Service Price",
  "vat": "VAT",
  "total_amount": "Total Amount",
  "confirm_book": "Confirm Book",
  "customer_id_missing": "Customer ID missing",
  "please_select_a_vehicle": "Please select a vehicle",
  "please_select_a_time_slot": "Please select a time slot",
  "invalid_slot_selected": "Invalid slot selected",
  "please_select_a_slot": "Please select a slot",
  "booking_updated_successfully": "Booking Updated Successfully!",
  "failed_to_update_booking": "Failed to update booking",
  "booking_failed": "Booking failed",
  "booking_failed_try_again": "Booking failed. Try again.",
  "location_saved": "Location saved",
  "error_selecting_location": "Error selecting location:",
  "your_coupon": "Your Coupon",
  "coupon_not_available": "Coupon not available",
  "valid_till": "Valid till",
  "done": "Done",
  "booking_confirmed": "Booking Confirmed!",
  "total": "Total",
  "door_step_services": "Door Step Services",
  "in_store_locations": "In-Store Locations",
  "search_by_name_or_area": "Search by name or area",
  "no_reviews_yet": "No reviews yet",
  "view_reviews": "View Reviews",
  "location": "Location",
  "call": "Call",
  "partner_locations_not_found":
      "We couldn't find any partner locations. Try again later.",
  "pick_location": "Pick Location",
  "selected_location": "Selected Location",
  "confirm_location": "Confirm Location",
  "error": "Error",
  "please_select_a_location": "Please select a location",
  "payment_details": "Payment Details",
  "confirm_service_details_before_payment":
      "Confirm your service details before proceeding to payment.",
  "subtotal": "Subtotal",
  "tax": "Tax",
  "pay_now": "Pay Now",
  "payment_failed": "Payment failed",
  "payment_successful": "Payment Successful",
  "tracking_service": "Tracking service",
  "live": "Live",
  "expected_soon": "Expected soon",
  "scheduled_at": "Scheduled at",
  "technician_assigned": "Technician Assigned",
};
